# Generated by Django 4.2.9 on 2024-01-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
        ('users', '0002_hospital'),
    ]

    operations = [
    ]
