# Generated by Django 4.2.9 on 2024-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_alter_user_password_0002_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='pdf',
        ),
        migrations.AddField(
            model_name='hospital',
            name='certificate',
            field=models.FileField(default='path/to/default/certificate.pdf', upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
